repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: system
        types_or: [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      # https://github.com/pre-commit/mirrors-mypy
      - id: mypy
        name: mypy
        description: ''
        entry: mypy
        language: system
        types_or: [python, pyi]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: '2.9.2'

      - id: pack
        name: pack
        description: "Create the pyz files"
        entry: python makepyz onepack
        language: system
        types_or: [python, pyi]
        pass_filenames: false
        always_run: true
